"""empty message

Revision ID: 1ea119b393b5
Revises: 
Create Date: 2022-09-06 14:39:48.424886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea119b393b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventurers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('careful', sa.Integer(), nullable=True),
    sa.Column('flashy', sa.Integer(), nullable=True),
    sa.Column('quick', sa.Integer(), nullable=True),
    sa.Column('strong', sa.Integer(), nullable=True),
    sa.Column('clever', sa.Integer(), nullable=True),
    sa.Column('sneaky', sa.Integer(), nullable=True),
    sa.Column('rich', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('fate', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adventurers')
    # ### end Alembic commands ###
