"""add exp

Revision ID: 5b8fb4a24a88
Revises: 03c44c9e2334
Create Date: 2021-10-25 08:07:19.012547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8fb4a24a88'
down_revision = '03c44c9e2334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventurers', sa.Column('exp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adventurers', 'exp')
    # ### end Alembic commands ###
